version: "3"

services:
  sonarqube:
    image: sonarqube:latest
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    restart: unless-stopped

  db:
    image: postgres:alpine
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

  reverse_proxy:
    container_name: reverse_proxy
    depends_on:
      - sonarqube
    image: nginx
    entrypoint:
      - sh
      - /etc/nginx/nginx.sh
    networks:
      - sonarnet
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.sh:/etc/nginx/nginx.sh
      - ./vol/letsencrypt:/etc/letsencrypt
      # - /etc/madridcentral/sonarqube.crt:/etc/ssl/certs/sonarqube.crt
      # - /etc/madridcentral/sonarqube.key:/etc/ssl/private/sonarqube.key

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data: