version: "3"

services:
  sonarqube:
    image: sonarqube:latest
    depends_on:
      - db
    networks:
      - sonarnet
      - nginx-proxy
    env_file:
      - .env
    expose:
      - "9000"
    environment:
      - VIRTUAL_HOST=sonarqube.ulagos.cl
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=https
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    restart: unless-stopped

  db:
    image: postgres:alpine
    networks:
      - sonarnet
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  sonarnet:
    driver: bridge
  default:
    external:
      name: nginx-proxy

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data: